// Auto-generated file
#pragma once


enum class PanelId {
	BUILDING_HOME,
	BUILDING_OIL_FIELD,
	BUILDING_PLANTATION,
	BUILDING_GROCERY,
	BUILDING_CONSTRUCTION,
	BUILDING_WAREHOUSE,
	JOB_OIL_FIELD,
};
